medicine/urls.py
from django.views.generic import TemplateView
from django.urls import path

from medicine.views import MListView, MDetailView, MCreateView, MUpdateView, MDeleteView

app_name = 'medicine'

urlpatterns = [
    path('', MListView.as_view(), name='list'),
    path('medicine/<int:pk>/', MDetailView.as_view(), name='detail'),
    path('medicine/create/', MCreateView.as_view(), name='create'),
    path('medicine/<int:pk>/update/', MUpdateView.as_view(), name='update'),
    path('medicine/<int:pk>/delete/', MDeleteView.as_view(), name='delete'),
]

pharmacy/urls.py
from django.urls import path, include
# from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from medicine.admin import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medicine.urls')),
    # Authentication
    path('users/', include('users.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from .views import SignUpView, CustomLoginView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

medicine/models.py
from django.contrib.auth.models import User
from django.db import models

class Medicine(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        permissions = [
            ("can_delete", "Can delete!!!!"),
        ]
    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

medicine/forms.py
from django import forms
from .models import Medicine


class MedisineForm(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = ['title', 'description', 'image']

medicine/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Medicine


class MListView(ListView):
    model = Medicine
    template_name = 'medicine/list.html'
    context_object_name = 'medicine'


class MDetailView(DetailView):
    model = Medicine
    template_name = 'medicine/detail.html'
    context_object_name = 'medicine'


class MCreateView(LoginRequiredMixin, CreateView):
    model = Medicine
    fields = ['title', 'description', 'image']
    template_name = 'medicine/create.html'
    success_url = reverse_lazy('medicine:list')

    def form_valid(self, form):
        form.instance.submitter = self.request.user

        return super().form_valid(form)


class UserIsSubmitter(UserPassesTestMixin):
    # Custom method
    def get_photo(self):
        return get_object_or_404(Medicine, pk=self.kwargs.get('pk'))

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry you are not allowed here')


class OwnerMixin(object):
    def get_queryset(self):
        qs = super(OwnerMixin, self).get_queryset()
        return qs.filter(submitter=self.request.user)


# class PhotoUpdateView(UserPassesTestMixin, UpdateView):
class MUpdateView(LoginRequiredMixin, OwnerMixin, UpdateView):
    template_name = 'medicine/update.html'
    model = Medicine
    fields = ['title', 'description', 'image']
    success_url = reverse_lazy('medicine:list')


class MDeleteView(PermissionRequiredMixin, DeleteView ):
    # specify the model you want to use
    model = Medicine
    success_url = reverse_lazy('medicine:list')
    template_name = 'medicine/delete.html'
    permission_required = 'medicine.can_delete'

users/views.py
from django.views.generic import CreateView

from django.contrib.auth import authenticate, login

from django.contrib.auth.views import LoginView

from django.contrib.auth.forms import UserCreationForm

from django.urls import reverse_lazy

class SignUpView(CreateView):

    template_name = 'users/signup.html'
    
    form_class = UserCreationForm

    success_url = reverse_lazy('photo:list')


    def form_valid(self, form):
        to_return = super().form_valid(form)

        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )

        login(self.request, user)

        return to_return
    
class CustomLoginView(LoginView):
    
    template_name = 'users/login.html'

medicine/templates/medicine/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Добавить</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Добавить</button>
  </form>
</div>
{% endblock body %}

medicine/templates/medicine/delete.html
{% extends 'base.html' %}

{% block body %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>: "<i
      >{{ medicine }}</i
    >
    "
  </h2>
  <p class="text-center">Are you sure, you want to delete the medicine ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'medicine:detail' medicine.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Удалить</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock body %}

medicine/templates/medicine/detail.html
{% extends 'base.html' %}

{% block body %}


<div class="mx-auto">
  <h1 class="text-center">{{ medicine.title }}</h1>
{#  <p class="text-center fw-light">Uploaded on: {{medicine.created}} <br> By {{medicine.submitter.username}}</p>#}
  {% if user == medicine.submitter %}
    <p class="text-center">
      <span><a href="#" class="text-primary px-2">Update</a></span>
      <span><a href="#" class="text-danger px-2">Delete</a></span>
    </p>
  {% endif %}
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{medicine.image.url}}" alt="" width="100%" />
  </div>
  <div class="col-md-4">
    <h4>More about this medicine:</h4>

    <p>{{ medicine.description }}</p>
  </div>
</div>

{% endblock body %}

medicine/templates/medicine/list.html
{% extends 'base.html' %}

{% block body %}

<div class="row">
  {% for photo in photos %}
    <div class="col-lg-3 col-md-4 col-xs-6">
        <i>{{ photo.submitter }}</i>
        <h3><a href="{% url 'medicine:detail' medicine.id  %}">{{ medicine.title }}</a></h3>
        <img src="{{ medicine.image.url }}" class="img-fluid" >
  </div>
  {% endfor %}
</div>

{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Med stock app</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar.html' %}

    <div class="container mt-4">

    {% block body %}
    
    {% endblock body %}
    
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">MED STOCK</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse flex-row-reverse"
        id="navbarTogglerDemo02"
      >
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
  
          <li class="nav-item">
            <a class="nav-link active" href="#">Add an item</a>
  {#          <a class="nav-link active" href="{% url 'medicine:create' %}">Add an item</a>#}
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Hi {{user.username}}</a>
          </li>
            <li class="nav-item">
  {#             <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>#}
  
  
              <form method="post" action="{% url 'users:logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Logout</button>
              </form>
  
            </li>
          {% else %}
  
          <li class="nav-item">
            <a href="{% url 'users:login' %}" class="btn btn-sm btn-danger"
              >Sign In</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Sign in</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Don't have an account?
      <a href="{% url 'users:signup' %}" class="text-primary ml-2">Create account</a>
    </p>
  </div>
</div>
{% endblock body %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Create account</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Already Registered?
      <a href="{% url 'users:login' %}" class="text-primary ml-2"> Login </a>
    </p>
  </div>
</div>
{% endblock body %}